# Generated by Django 2.0 on 2018-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='clap_num',
            field=models.IntegerField(default='0'),
        ),
    ]
